// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1qrRsp2dqKdtVa6x67r38Czm2LH3NXSA',
    appId: '1:552635757419:web:f0ffc7bc6cf09e8ba6522e',
    messagingSenderId: '552635757419',
    projectId: 'todolist-c63a3',
    authDomain: 'todolist-c63a3.firebaseapp.com',
    storageBucket: 'todolist-c63a3.appspot.com',
    measurementId: 'G-JP2MM96DHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCifLL-J_Gtjf0lHQ8_CsZD9iUEstbbGec',
    appId: '1:552635757419:android:506ca2a3d148b81ca6522e',
    messagingSenderId: '552635757419',
    projectId: 'todolist-c63a3',
    storageBucket: 'todolist-c63a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOTU_d2AinqOzugAB3OUWM6WmKr8yw6oQ',
    appId: '1:552635757419:ios:050fcaa78b29a2eea6522e',
    messagingSenderId: '552635757419',
    projectId: 'todolist-c63a3',
    storageBucket: 'todolist-c63a3.appspot.com',
    iosClientId:
        '552635757419-ja25hfiec2l2bnco6qep34fc38r8aru7.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOTU_d2AinqOzugAB3OUWM6WmKr8yw6oQ',
    appId: '1:552635757419:ios:de9eba38eb9fb3b9a6522e',
    messagingSenderId: '552635757419',
    projectId: 'todolist-c63a3',
    storageBucket: 'todolist-c63a3.appspot.com',
    iosClientId:
        '552635757419-1m5rvurkeuq6pa5aggsqujkrnbl3rs9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
